version: '3.7'
services:
  postgres-golang:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go-micro-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  mongo-golang:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
    networks:
      - go-micro-network

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - go-micro-network

  rabbitmq:
    image: 'rabbitmq:3.13.0-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - go-micro-network
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/data:/var/lib/rabbitmq
      - ./db-data/rabbitmq/log:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: '123456'


networks:
  go-micro-network:
    external: true

volumes:
  pgdata: